[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "cd client && npm install",
  "cd client && npm run build",
  "cd server && npm install --build-from-source sqlite3"
]

[start]
cmd = "cd server && NODE_ENV=production node app.js"
